REM   Script: Session 04
REM   station

CREATE TABLE STATION 
(ID MEMBER Primary Key, 
CITY CHAR(20), 
STATE CHAR(2), 
LAT_N REAL, 
LONG_W REAL);

INSERT INTO STATION VALUES (13,'Phoenix','AZ',33,112);

INSERT INTO STATION VALUES (44, 'Denver', 'CO', 40, 105);

INSERT INTO STATION VALUES (66, 'Caribou', 'ME', 47, 68);

CREATE TABLE STATION 
(ID MEMBER Primary Key, 
CITY CHAR(20), 
STATE CHAR(2), 
LAT_N REAL, 
LONG_W REAL);

INSERT INTO STATION VALUES (13,'Phoenix','AZ',33,112);

INSERT INTO STATION VALUES (44, 'Denver', 'CO', 40, 105);

INSERT INTO STATION VALUES (66, 'Caribou', 'ME', 47, 68);

SELECT * FROM STATION;

CREATE TABLE STATION 
(ID INTEGER PRIMARY KEY, 
CITY CHAR(20), 
STATE CHAR(2), 
LAT_N REAL, 
LONG_W REAL);

INSERT INTO STATION VALUES (13, 'Phoenix', 'AZ', 33, 112);

INSERT INTO STATION VALUES (44, 'Denver', 'CO', 40, 105);

INSERT INTO STATION VALUES (66, 'Caribou', 'ME', 47, 68);

SELECT * FROM STATION;

SELECT FROM * STATION 
WHERE LAT_N>39.7;

SELECT * FROM STATION;

WHERE LAT_N>39.7;


SELECT * FROM STATION;

WHERE LAT_N>39.7;


SELECT * FROM STATION;

WHERE LAT_N>39.7;


WHERE LAT_N>39.7;


SELECT * FROM STATION 
WHERE LAT_N>39.7;

SELECT * FROM STATION 
WHERE LAT_N>39.7;

SELECT * FROM STATION 
WHERE LAT_N>39.7;

SELECT * FROM STATION 
WHERE LAT_N>39.7;

CREATE TABLE STATION 
(ID INTEGER PRIMARY KEY, 
CITY CHAR(20), 
STATE CHAR(2), 
LAT_N REAL, 
LONG_W REAL);

INSERT INTO STATION VALUES (13, 'Phoenix', 'AZ', 33, 112);

INSERT INTO STATION VALUES (44, 'Denver', 'CO', 40, 105);

INSERT INTO STATION VALUES (66, 'Caribou', 'ME', 47, 68);

CREATE TABLE STATION 
(ID INTEGER PRIMARY KEY, 
CITY CHAR(20), 
STATE CHAR(2), 
LAT_N REAL, 
LONG_W REAL);

INSERT INTO STATION VALUES (13, 'Phoenix', 'AZ', 33, 112);

INSERT INTO STATION VALUES (44, 'Denver', 'CO', 40, 105);

INSERT INTO STATION VALUES (66, 'Caribou', 'ME', 47, 68);

SELECT * FROM STATION;

